server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: C##GOZIN
    password: GOZIN
  web:
    resources:
      static-locations: classpath:/productimgs/

# 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  # WebConfig에 세팅
  add-resource-locations: classpath:/static/productimgs/
  add-resource-handler: /productimgs/**
  # ProductService에 세팅
  image-dir: src/main/resources/static/productimgs
  image-url: http://localhost:8080/productimgs/


jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.gozin.mainboard
  configuration:
    map-underscore-to-camel-case: true