server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: C##GOZIN
    password: GOZIN

jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.gozin.mainboard
  configuration:
    map-underscore-to-camel-case: true