-- 2022/10/08 수정 로그
/* 요청자 : 차용준 | 수정 내용 : 데이터 최대값 수정 및 삭제 컬럼 다른 테이블에 추가  */
ALTER TABLE TB_PAYMENT_HISTORY MODIFY PAYMENT_CODE VARCHAR2(60);
ALTER TABLE TB_PAYMENT_HISTORY DROP COLUMN MEMBER_CODE;
ALTER TABLE TB_PAYMENT_HISTORY DROP COLUMN PAYMENT_METHOD;
ALTER TABLE TB_PAYMENT_HISTORY DROP COLUMN DELIVERY_CHARGE;
ALTER TABLE TB_PAYMENT_HISTORY DROP COLUMN COUPON_USED_AMOUNT;
ALTER TABLE TB_PAYMENT_HISTORY DROP COLUMN POINTS_USED_AMOUNT;
ALTER TABLE TB_PAYMENT_HISTORY DROP COLUMN FINAL_PAYMENT_AMOUNT;
ALTER TABLE TB_PAYMENT_HISTORY DROP COLUMN PAYMENT_STATUS;
ALTER TABLE TB_PAYMENT_HISTORY DROP COLUMN CHANGE_CODE;
ALTER TABLE TB_PAYMENT_HISTORY DROP COLUMN HOLD_COUPON_CODE;
ALTER TABLE TB_ORDER ADD MEMBER_CODE VARCHAR2(20) NOT NULL;
ALTER TABLE TB_ORDER ADD PAYMENT_METHOD VARCHAR2(20) NOT NULL;
ALTER TABLE TB_ORDER ADD DELIVERY_CHARGE NUMBER NOT NULL;
ALTER TABLE TB_ORDER ADD COUPON_USED_AMOUNT NUMBER;
ALTER TABLE TB_ORDER ADD POINTS_USED_AMOUNT NUMBER;
ALTER TABLE TB_ORDER ADD FINAL_PAYMENT_AMOUNT NUMBER NOT NULL;
ALTER TABLE TB_ORDER ADD PAYMENT_STATUS VARCHAR2(10) NOT NULL;
ALTER TABLE TB_ORDER ADD CHANGE_CODE VARCHAR2(20) NOT NULL;
ALTER TABLE TB_ORDER ADD HOLD_COUPON_CODE VARCHAR2(20) NOT NULL;

/* 요청자 : 이유리 | 수정 내용 : DEFAULT 값 및 CHECK 제약 조건 추가 */
ALTER TABLE TB_MEMBER MODIFY MEMBER_ROLE DEFAULT 'ROLE_MEMBER';

ALTER TABLE TB_MEMBER ADD CONSTRAINT CHK_MEMBER_ROLE
    CHECK(MEMBER_ROLE IN ('ROLE_MEMBER', 'ROLE_ADMIN'));

/* 요청자 : 손준형 | 수정 내용 : 컬럼명 및 코멘트 변경 */
ALTER TABLE TB_BOARDGAME_RATE RENAME COLUMN RATE_DISCOUNT TO DISCOUNT_PRICE;
COMMENT ON COLUMN TB_BOARDGAME_RATE.DISCOUNT_PRICE IS '할인가격';

COMMIT;